FROM ubuntu

RUN apt-get update && apt-get install -y gnupg

# Install Java.
RUN apt-get update && apt-get install -q -y \
      default-jdk \
      sudo \
      apt-transport-https

# Install gauge
RUN apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B && \
    echo deb https://dl.bintray.com/gauge/gauge-deb stable main | sudo tee -a /etc/apt/sources.list

RUN apt-get update && apt-get install gauge
# Install gauge plugins
RUN gauge install java && \
    gauge install screenshot

ENV PATH=$HOME/.gauge:$PATH
